# Generated by Django 2.1.3 on 2018-12-29 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('username', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True, verbose_name='学号')),
                ('password', models.CharField(default='', max_length=20, verbose_name='密码')),
                ('studentname', models.CharField(default='', max_length=10, verbose_name='姓名')),
                ('wxid', models.CharField(default='', max_length=50, verbose_name='微信openid')),
                ('autologin', models.IntegerField(default=0, verbose_name='是否自动登录')),
                ('sex', models.CharField(default='', max_length=5, verbose_name='性别')),
                ('CET_number', models.CharField(default='', max_length=20, verbose_name='四六级考号')),
                ('classname', models.CharField(default='', max_length=10, verbose_name='班名')),
                ('professional', models.CharField(default='', max_length=30, verbose_name='专业')),
                ('college', models.CharField(default='', max_length=20, verbose_name='学院')),
                ('campus', models.CharField(default='', max_length=10, verbose_name='校区')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
        ),
    ]
